language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - nightly

before_script:
  - julia build_unregistered_packages.jl              # make sure package is available

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#   - julia: nightly

notifications:
  email: false

# Uncomment to use non-default scrip
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("FastBGCParameterOptimization"); Pkg.test("FastBGCParameterOptimization"; coverage=true)';

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("FastBGCParameterOptimization")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("FastBGCParameterOptimization")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';